### ISSUE TITLE
evaluate quiz response 

### ISSUE THREAD

**Issue by sohm22** [sohm22/quizapp#40]
expose api to evaluate Quiz 
and send response with evaluation

**Comment by ramsaoji** [comment]
Payload - `{
  "operationName": "SubmitQuiz",
  "variables": {
    "quizId": "64fcbf1a2f74a2e8e8a12d34",
    "answers": [
      {
        "questionId": "64fcbf1a2f74a2e8e8a12d35",
        "selectedAnswer": "State Management"
      },
      {
        "questionId": "64fcbf1a2f74a2e8e8a12d36",
        "selectedAnswer": "setState()"
      },
      {
        "questionId": "64fcbf1a2f74a2e8e8a12d37",
        "selectedAnswer": "componentWillMount"
      },
      {
        "questionId": "64fcbf1a2f74a2e8e8a12d3c",
        "selectedAnswer": "To manage component lifecycle"
      },
      {
        "questionId": "64fcbf1a2f74a2e8e8a12d3e",
        "selectedAnswer": "A state management library"
      }
    ]
  },
  "query": "mutation SubmitQuiz($quizId: ID!, $answers: [AnswerInput!]!) {\n  submitQuiz(quizId: $quizId, answers: $answers) {\n    score\n    feedback {\n      correctAnswer\n      isCorrect\n      __typename\n    }\n    __typename\n  }\n}"
}`

Response - `{
    "data": {
        "submitQuiz": {
            "score": 1,
            "feedback": [
                {
                    "correctAnswer": "Building User Interfaces",
                    "isCorrect": false,
                    "__typename": "QuestionFeedback"
                },
                {
                    "correctAnswer": "setState()",
                    "isCorrect": true,
                    "__typename": "QuestionFeedback"
                },
                {
                    "correctAnswer": "componentDidMount",
                    "isCorrect": false,
                    "__typename": "QuestionFeedback"
                },
                {
                    "correctAnswer": "To manage state in functional components",
                    "isCorrect": false,
                    "__typename": "QuestionFeedback"
                },
                {
                    "correctAnswer": "A syntax extension for JavaScript that looks similar to HTML",
                    "isCorrect": false,
                    "__typename": "QuestionFeedback"
                }
            ],
            "__typename": "QuizResult"
        }
    }
}`

**Comment by sohm22** [comment]
```{
  "operationName": "SubmitQuiz",
  "variables": {
    "quizId": "64fcbf1a2f74a2e8e8a12d34",
    "answers": [
      {
        "questionId": "64fcbf1a2f74a2e8e8a12d35",
        "selectedAnswer": "State Management"
      },
      {
        "questionId": "64fcbf1a2f74a2e8e8a12d36",
        "selectedAnswer": "setState()"
      },
      {
        "questionId": "64fcbf1a2f74a2e8e8a12d37",
        "selectedAnswer": "componentWillMount"
      },
      {
        "questionId": "64fcbf1a2f74a2e8e8a12d3c",
        "selectedAnswer": "To manage component lifecycle"
      },
      {
        "questionId": "64fcbf1a2f74a2e8e8a12d3e",
        "selectedAnswer": "A state management library"
      }
    ]
  },
  "query": "mutation SubmitQuiz($quizId: ID!, $answers: [AnswerInput!]!) {\n  submitQuiz(quizId: $quizId, answers: $answers) {\n    score\n    feedback {\n      correctAnswer\n      isCorrect\n      __typename\n    }\n    __typename\n  }\n}"
}```





Prompt
```
You are an AI assistant specialized in generating quizzes on well-defined programming topics.
        Before generating a quiz, ensure the following conditions are met:
        -The prompt must include a specific programming language and a programming concept or topic. The description or context can be general but should indicate the main focus of the quiz (e.g., 'Python quiz on Flask topics').
        -If the prompt is too vague or lacks enough detail about the specific aspect of the topic, req
```
